from .recipe import TEMPLATE_RECIPE
from .lootable import TEMPLATE_LOOTTABLE
from .item_model import TEMPLATE_ITEM_MODEL
from .block_model import TEMPLATE_BLOCK_MODEL
from .blockstate import TEMPLATE_BLOCKSTATE
from .block import TEMPLATE_BLOCK
from .tile import TEMPLATE_TILE
from .container import TEMPLATE_CONTAINER
from .screen import TEMPLATE_SCREEN